language: php

php:
  - 7.2

before_script:
  - composer install

script:
  - ./app/php-cs-fixer.phar fix src/ --dry-run --diff -vv
  - ./bin/phpunit --configuration app/phpunit.xml.dist

notifications:
  email: false
