services:
    app.twig_code_club_extension:
        class: CodeClubBundle\Twig\CodeClubExtension
        arguments:
            - "@club_manager"
        tags:
            - { name: twig.extension }
    club_manager:
        class: CodeClubBundle\Service\ClubManager
        arguments:
            - "@request_stack"
    club_registration:
        class: CodeClubBundle\Service\ClubRegistration
        arguments:
            - "@mailer"
            - "@user.registration"
            - "%base_host%"
    current_club_listener:
        class: CodeClubBundle\EventListener\CurrentClubListener
        arguments:
            - "@club_manager"
            - "@doctrine.orm.default_entity_manager"
            - "%base_host%"
            - "@logger"
        tags:
            -
                name: kernel.event_listener
                event: kernel.request
                method: onKernelRequest
                priority: 11
