imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: critical
            handler: grouped
        grouped:
            type:    group
            members: [streamed, buffered]
        streamed:
            type:  stream
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
        buffered:
            type:  buffer
            handler: swift
        swift:
            type: swift_mailer
            from_email: '%default_mail%'
            to_email: '%webmaster_mail%'
            subject: An Error Occurred on trondheim.kodeklubben.no!
            level: debug

doctrine:
    dbal:
        path: "%kernel.root_dir%/data/prod.db"
        driver: pdo_sqlite
        host: localhost
        port: null
        dbname: "%kernel.root_dir%/data/prod.db"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
